services:
    tabby:
        build: .
        restart: always
        depends_on:
            - tabby-db
        environment:
        - DATABASE_URL=mysql://tabby:yf^!FThbPK833Q@db/tabby
        - PORT=80
        - DEBUG=False
        - DOCKERIZE_ARGS="-wait tcp://tabby-db:3306 -timeout 60s"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.tabby.rule=Host(`tabby.avila-fernandes.com`)"
            - "traefik.http.routers.tabby.entrypoints=websecure"
            - "traefik.http.routers.tabby.tls.certresolver=letsencrypt"
            - "traefik.http.services.tabby.loadbalancer.server.port=80"
        networks:
            - frontend 
            - backend


    tabby-db:
        image: mariadb
        restart: always
        environment:
            MARIADB_DATABASE: tabby
            MARIADB_USER: tabby
            MARIADB_PASSWORD: yf^!FThbPK833Q
            MYSQL_ROOT_PASSWORD: AN7dau%7%2#wLm
        volumes:
            - tabby-db:/var/lib/mysql
        networks:
            - backend

volumes:
    tabby-db:
        external: true